sudo: required
services:
    - docker
language: bash
script:
# build image
- docker build -t semaph0r/rsbb .
# push image
- echo "DOCKER_PASS" | docker login -u="$DOCKER_USER" --password-stdin
- docker tag semaph0r/rsbb semaph0r/rsbb:latest
- docker push semaph0r/rsbb
